### ISSUE TITLE
Is this library that much stable to use in Production App ? Please guide me

### ISSUE THREAD

**Issue by kadnan0900** [fluttercommunity/flutter_uploader#103]

**Comment by ened** [comment]
We use it in production successfully. If you have specific issues, please don't hesitate to open them on Github.

**Comment by kadnan0900** [comment]
@ened when you will update this library because i see their was a last update of Stable versions of flutter_uploader on 
1.2.0 | Nov 5, 2019 because i have to use this library in my production app and i am really excited to use this lib in my app.

**Comment by ened** [comment]
@kadnan0900 I suggest you start by testing the beta version of the plugin in your app and report issues.
