### ISSUE TITLE
Error when  try use 'flutter build apk'

### ISSUE THREAD

**Issue by Konoshenko** [fluttercommunity/flutter_uploader#104]
* Where:
Settings file 'C:\dev\flutter\.pub-cache\git\flutter_uploader-a93e43324fc4f0689e42b80972f1443145d9a088\android\settings.gradle' line: 2

* What went wrong:
A problem occurred evaluating settings 'flutter_uploader'.
> Could not get unknown property 'android' for settings 'flutter_uploader' of type org.gradle.initialization.DefaultSettings.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

**Comment by ened** [comment]
Dear @Konoshenko could you please share more details on the environment and of course which version of the plugin are you using? Is it the beta version from `pub`?

**Comment by Konoshenko** [comment]
@ened 
I`m use version:
`flutter_uploader: ^2.0.0-beta.3.`
And my flutter:
```
Flutter 1.20.0 • channel beta • https://github.com/flutter/flutter.git
Framework • revision e606910f28 (2 months ago) • 2020-07-28 16:06:37 -0700
Engine • revision ac95267aef
Tools • Dart 2.9.0 (build 2.9.0-21.10.beta)

```

**Comment by volser** [comment]
I got the same error

**Comment by ened** [comment]
Hi there, AGP 4.x is not yet support by Flutter: https://github.com/flutter/flutter/issues/58247.
Assuming you both run into this and therefore will close the ticket.
