### ISSUE TITLE
Upload file from ram without using file path

### ISSUE THREAD

**Issue by MohammedYAmmar** [fluttercommunity/flutter_uploader#105]
Upload file directly from ram without using file path

**Comment by agnoam** [comment]
You can take your `Uint8ByteCode` put it in a temporary file, and give the `FlutterUploader()` the path of the temp file.
After it finishes you can run a callback function that will delete those files.

**Comment by ened** [comment]
This is out of scope for this plugin, sorry. The upload will potentially run when the App is NOT running, thus the file needs to be available from disk.
