### ISSUE TITLE
Terminated mode in 1.2.0

### ISSUE THREAD

**Issue by AhmedNourJamalElDin** [fluttercommunity/flutter_uploader#106]
Hello,

I would like to know if the file is uploaded or failed if the application is in terminated mode.

As I see in the doc there is a background handler that does the job but it's not in version `1.2.0`. is there any way to do this in `1.2.0` or I have to update to v2.

Do you plan to publish the newer version to pub.dev soon? should I switch to master version?

Thanks

**Comment by ened** [comment]
The background handler is only available in 2.0 onwards and it's available from pub as well.

**Comment by AhmedNourJamalElDin** [comment]
Oh it is a prerelease.
Thanks
