### ISSUE TITLE
How to get Tag in the result or progress streams

### ISSUE THREAD

**Issue by AhmedNourJamalElDin** [fluttercommunity/flutter_uploader#107]
Hello,

I am using version `2.0.0-beta.3` and I would like to use the tag attribute.
As stated in the documentation, 

>     tag: 'my tag', // custom tag which is returned in result/progress

I should be able to access it, and I have tried something like this:

```dart
uploader.result.listen((event) {
       final tag = event.tag;
});
```

but it didn't work because UploadTaskResponse has no attribute called tag.

so the question is how to access it?

**Comment by ened** [comment]
@AhmedNourJamalElDin `tag` is currently used internally only - but I will try to reactivate it. It is likely to become a list of tags which you can assign.

**Comment by AhmedNourJamalElDin** [comment]
Thanks for response.
I am no longer uploading files in background i.e. I'm not using this package at thr moment.

Accordingly, I will close this issue.

**Comment by aaqibism** [comment]
Will it be possible to activate tag or a custom attribute of some sort in future versions? The main reason I want it is because I want to watch the show the progress of potentially multiple uploads to a user, but for now it's impossible to do so because I cannot determine which UploadProgress corresponds to the one shown in the UI. Thank you for the help.

**Comment by ened** [comment]
@aaqibism yes - that is probably a good way. 

Are you interested in documenting your approach in the Wiki? Others may find it helpful.

**Comment by aaqibism** [comment]
Sure, that sounds interesting. Although I’m not entirely if I chose the best solution for communicating between isolates. I ended up using a Send and Receive port as I found most reliable.

**Comment by ened** [comment]
Send & Receive Port is a good way. You can use IsolateNameServer to register by name etc. There are a few caveats like timeouts, receiver gone, response missing etc..

**Comment by aaqibism** [comment]
@ened Would you still like me to document on the Wiki or no?
