### ISSUE TITLE
Hot reload after upload will cause error

### ISSUE THREAD

**Issue by MICKEY88661** [fluttercommunity/flutter_uploader#108]
I'm using 

> flutter_uploader: ^2.0.0-beta.3

and this is my flutter doctor:

> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel unknown, v1.17.0, on Mac OS X 10.15.6 19G73, locale zh-Hant-TW)
> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
> [✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
> [✓] Android Studio (version 4.0)
> [✓] Connected device (1 available)
> 
> • No issues found!

And I'm running my project on an ios emulator.
No error comes out before or after I upload an image, but once I hot reload, it comes out 

> Error -32601 received from application: Method not found
> Error -32601 received from application: Method not found
> Error -32601 received from application: Method not found
> Error -32601 received from application: Method not found
> Error -32601 received from application: Method not found
> Error -32601 received from application: Method not found
> Error -32601 received from application: Method not found
> Error -32601 received from application: Method not found
> Reloaded 362 of 1852 libraries in 1,688ms.

I'm not sure if it related to isolates? Can someone give me an answer?

**Comment by ened** [comment]
@MICKEY88661 I'm currently not sure what the detail issue is here. Please try with the latest version & also share reproducible steps. Please re-open the ticket if you have more information.
