### ISSUE TITLE
支持分段上传吗？

### ISSUE THREAD

**Issue by jeromekai** [fluttercommunity/flutter_uploader#109]

**Comment by ened** [comment]
The question translates "支持分段上传吗" => Do you support multipart upload?

The answer for that is **yes**. Please ask any follow up questions in English, though. Thank you.

**Comment by jeromekai** [comment]
support multipart upload？




---原始邮件---
发件人: "Sebastian Roth"<notifications@github.com&gt;
发送时间: 2020年10月16日(周五) 晚上8:22
收件人: "fluttercommunity/flutter_uploader"<flutter_uploader@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"Jerome"<1641194779@qq.com&gt;;
主题: Re: [fluttercommunity/flutter_uploader] 支持分段上传吗？ (#109)




 
The question translates "支持分段上传吗" =&gt; Do you support multipart upload?
 
The answer for that is yes. Please ask any follow up questions in English, though. Thank you.
