### ISSUE TITLE
Need to track the progress based on particular taskId

### ISSUE THREAD

**Issue by Dheena32** [fluttercommunity/flutter_uploader#110]
I got the taskId but how to track the progress or result for that particular taskId

**Comment by kadnan0900** [comment]
@Dheena32 did you find any solution ?

**Comment by Dheena32** [comment]
No, i didnt got any solution

**Comment by AngelDevs** [comment]
hello @Dheena32. 

the steps that i take to do this is:
1 - Create a class to hold the data of the files that i will upload like [progress] and [status]. (let's call it [UploadItem]). 
2 - Create a stream subscription that will listen for the progress. (there is a property [FlutterUploader().progress]) 
3 - when i upload a file, i create and hold the state of a new [UploadItem] 
4 - the progress stream has a [UploadTaskProgress] value that has the [taskId], [progress], [tag] etc. so every time the stream receives a progress i check in my state for the upload item that match the [taskId] or the [tag], then i update that value with the new one. 

some points: 
1 - I use flutter_bloc with an UploadBloc that is in charge of all this job 
2 - I use flutter_uploader 1.2 ( not the pre release version) 

for the [status] i do the same, create a stream with [FlutterUploader().result] 

i hope this works for you, sorry if i misunderstood your problem or this does't work for you. by the way, i saw this approach in the example of the flutter_uploader 1.2

**Comment by ened** [comment]
I think you have found a solution?
