### ISSUE TITLE
data param should allow <String, dynamic>

### ISSUE THREAD

**Issue by Dheena32** [fluttercommunity/flutter_uploader#111]
As of now data param allowing only <String, String>
Please add provision for allowing <String, dynamic>
so that we can send multiple level of json format like ,
   { product: {
    name: ['Apple', 'Orange']
     }
   }

**Comment by ened** [comment]
@Dheena32 I'm thinking to replace the data parameter with a generic ByteList, so that you could send anything you'd like. The uploader is currently forcing JSON but it should really be up to the API user. Thx for the feedback.
