### ISSUE TITLE
Upload task stops after uploading files and does not return the result and status. Android only.

### ISSUE THREAD

**Issue by ykiran** [fluttercommunity/flutter_uploader#117]
### Flutter Doctor -v output
> [√] Flutter (Channel stable, v1.17.4, on Microsoft Windows [Version 6.1.7601],
>     locale en-US)
>     • Flutter version 1.17.4 at H:\flutter_v1.17.4\flutter
>     • Framework revision 1ad9baa8b9 (5 months ago), 2020-06-17 14:41:16 -0700
>     • Engine revision ee76268252
>     • Dart version 2.8.4
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
>     • Android SDK at E:\AndroidSDK
>     • Platform android-29, build-tools 29.0.3
>     • ANDROID_HOME = E:\AndroidSDK
>     • ANDROID_SDK_ROOT = E:\AndroidSDK
>     • Java binary at: c:\programdata\Oracle\Java\javapath\java.exe
>     • Java version Java(TM) SE Runtime Environment (build 1.8.0_66-b18)
>     • All Android licenses accepted.
> 
> [!] Android Studio
>     • Android Studio at C:\Program Files\Android\Android Studio"
>     X Flutter plugin not installed; this adds Flutter specific functionality.
>     X Dart plugin not installed; this adds Dart specific functionality.
>     X android-studio-dir = C:\Program Files\Android\Android Studio"
>     X Android Studio not found at C:\Program Files\Android\Android Studio"
>     • Try updating or re-installing Android Studio.
>     • Consider removing your android-studio-dir setting by running:
>       flutter config --android-studio-dir=
> 
> [√] VS Code (version 1.51.0)
>     • VS Code at C:\Users\XXX\AppData\Local\Programs\Microsoft VS Code
>     • Flutter extension version 3.16.0
> 
> [√] Connected device (1 available)
>     • Mi A3 • 9XXXXX • android-arm64 • Android 10 (API 29)

### New upload task
```dart
Future<FlutterUploader> uploadImages(Map uploadData) {
 final taskId = await _uploader.enqueue(
        url: url,
        files: List<FileItem> images,
        method: UploadMethod.POST,
        headers: {"our headers"},
        data: {
          "field1": uploadData["f1"],
          "field2": uploadData["f2"],
          "field3": uploadData["f3"],
        },
        showNotification: false,
        tag: some_uniqid,
      );
 return _uploader;
}
```
### Invocation
```dart
for(int i=0;i<batches.size;i++) {
    FlutterUploader _uploader = await uploadImages(myMap);

    final _subscription = _uploader.progress.listen((prg) {
       print(prg.progress);
    });

    await for (var res in _uploader.result) {
     if (res.status == UploadTaskStatus.failed) {
        //Set flags and move on
      }
      if (res.status == UploadTaskStatus.complete) {
        //Update db and move on
      }
    }
}

```

### Issue in detail
We have a bunch of images that need to be uploaded. Every image uploaded will have a flag set in the database.
Once all the images are uploaded, the task flag will be set in the db.
As such, we have broken down the images into batches of 5 each.
Using this strategy worked very well in the IOS version.

In Android, when the first batch is uploaded, there is no further movement. 
We are not getting any data into the progress and the result status listeners.
The debug output shows the following:

> D/UploadWorker(31452): Response: {json response from the server}
D/UploadWorker(31452): Response header: {"date":"Fri, 06 Nov 2020 13:37:15 GMT","set-cookie":"ARRAffinitySameSite\......}
I/WM-WorkerWrapper(31452): Worker result SUCCESS for Work [ id=64bdcc95-1ef9-4b9f-959f-bc8420db9336, tags={ flutter_upload_task, com.bluechilli.flutteruploader.UploadWorker } ]

And that is all. Nothing until we restart the process again.
Then the same thing happens, all the files get uploaded and the task stops there.

This happens only in Android and the same code works perfectly fine in IOS.
Checked in versions 9 and 10.
Working in 11.

**Comment by ened** [comment]
Please test again using 2.0.0-beta.4.
