### ISSUE TITLE
In the android source code, the “clearUploads” method is incomplete

### ISSUE THREAD

**Issue by jeromekai** [fluttercommunity/flutter_uploader#119]
In the android source code, the clearUploads method is incomplete. Are you considering adding a cache cleaning and database cleaning?
Now you can only release the cache by exiting the application.
version 2.0.0-beta3.0

**Comment by ened** [comment]
@jeromekai Good point, I'll need to check whether the `clearUploads` logic makes sense here. 

Android's WorkManager keeps a record of work done - in our case uploads finished. I am a bit hesitant to clear that as it's a single API and we may clear work that is not scheduled by the uploader, but instead could be created by the `workmanager` package.

**Comment by jeromekai** [comment]
Is there any other solution to clear the cache

**Comment by jeromekai** [comment]
I see a clear method related to the ios source code

**Comment by ened** [comment]
@jeromekai What problem are you facing with the current APIs?
What is working / not working or different than expected?

**Comment by jeromekai** [comment]
@ened Sometimes the upload list does not need to be visible every time, I hope this method is Clear the cache in the plugin while clearing the upload, or give a separate method to clear the cache

**Comment by UzairSun93** [comment]
Somehow i am facing the same issue ... can we delete or remove the specific task from cache, because   (StreamSubscription<UploadTaskResponse> _resultSubscription );  will give us all the results every time 
...??

**Comment by ened** [comment]
@jeromekai @UzairSun93 understood. Will take a detail look asap.

**Comment by ened** [comment]
@jeromekai @UzairSun93 - this will be resolved in the upcoming version `2.0.0-beta.4`
