### ISSUE TITLE
uploader.result.listen call too many times 

### ISSUE THREAD

**Issue by kadnan0900** [fluttercommunity/flutter_uploader#122]
` uploader.result.listen((result) async {
          print("response " + result.response);
        }, onError: (ex, stacktrace) {
          print(ex.toString());
        });
 }`

When first time I call this, uploader.result.listen will only print one. But if I call this method again, uploader.result.listen will call almost 10 to 16 times. Why?

Version 2.0.0-beta.3

**Comment by kadnan0900** [comment]
<key>FUMaximumUploadOperation</key>
<integer>3</integer>
IOS app crash which i configure 3 number of concurrent task

**Comment by kadnan0900** [comment]
i want to use this library in production app please release a stable version because i am facing too many issues in Version 2.0.0-beta.3

**Comment by kadnan0900** [comment]
how i can delete the specific task from cache ?

**Comment by kadnan0900** [comment]
Some tasks i can not resume after connection recovery ?

**Comment by ened** [comment]
@kadnan0900 can you share more details on:

> When first time I call this, uploader.result.listen will only print one. But if I call this method again, uploader.result.listen will call almost 10 to 16 times. Why?

Is this in the simulator or a actual device?

> FUMaximumUploadOperation
> 3
> IOS app crash which i configure 3 number of concurrent task

Please share a stack trace or similar, I will look at this now.

> how i can delete the specific task from cache ?

This function is not available yet, will look at it now.

> Some tasks i can not resume after connection recovery ?

Please outline your test case.

**Comment by ened** [comment]
@kadnan0900 can you please check the latest version 2.0.0-beta.4 and also see the documentation. For specific problems, please open separate issues with detailed test instructions.
