### ISSUE TITLE
Can't able to upload file from ios 

### ISSUE THREAD

**Issue by UzairSun93** [fluttercommunity/flutter_uploader#131]
i am unable to sent a file from ios ... our app server didn't receive any data when i post the request from iphone ? In android its working fine .. 

Here is my code :

 //this function will uploads file using flutter uploader

  Upload _buildUpload(String path, String token, Con.Data data, String mobID) {
    final tag = 'upload';
    Map<String, String> header = new Map();

    header['Content-Type'] = 'application/json; charset=utf-8';
    // header['Content-Type'] = 'multipart/form-data; boundary=\(boundary)';

    if (token != null) {
      header.putIfAbsent(Endpoints.AUTH_HEADER, () => token);
    } else {
      print('Auth token is null');
    }
    

    return MultipartFormDataUpload(
      url: Endpoints.DEV_AWS_SERVER + Endpoints.UPLOAD_ATTACH,
      headers: header,
      data: {
        'job_id': data.containerDetails.jobId,
        'type_id': Constants.BLANKCONTAINER_TYPE.toString(),
        'container_id': data.containerDetails.id,
        'mob_id': mobID
      },
      files: [FileItem(path: path, field: 'file')],
      method: UploadMethod.POST,
      tag: tag,

    );
  }

**Comment by ened** [comment]
Please collect detailed logs when running your app through Xcode.

**Comment by UzairSun93** [comment]
Thanks for your immediate response ! i have just fixed that issue ...i think the problem was occurring when i manually put the "Content-type " in request header.. 
So i just remove that line :
header['Content-Type'] = 'application/json; charset=utf-8'; 

 Now it's working fine .
