### ISSUE TITLE
The application crashes after trying to upload a file.

### ISSUE THREAD

**Issue by Konoshenko** [fluttercommunity/flutter_uploader#132]
I add file in enqueue method [look screenshot]  
In previous package version 2.0.0-beta3 everything work fine.

This code snippet show how I handle download process. 
But I don't hit the listener breakpoints
```
_progressSubscription = _fileUploader.progress.listen((progress) {
      if ((progress.status == UploadTaskStatus.running &&
          progress.progress % 5 == 0) ||
          progress.status != UploadTaskStatus.running) {
        _uploadProgressController.add(UploadFileProgressEvent(
            progress.taskId, progress.status, progress.progress));
      }
    });

    _resultSubscription = _fileUploader.result.listen((result) {
      if (result.statusCode < 400) {
        _uploadStatusController.add(UploadFileStatusEvent(
            result.taskId, result.status, json.decode(result.response), false));
      } else {
        _uploadStatusController.add(UploadFileStatusEvent(
            result.taskId, result.status, null, true));
      }
    }, onError: (ex, stacktrace) {
      if (ex != null) {
        _uploadStatusController.add(UploadFileStatusEvent(
            ex.taskId,
            ex.status,
            {
              'message': ex.message,
              'code': ex.code,
              'statusCode': ex.statusCode
            },
            true));
      }
    });
```

<img width="1082" alt="Screenshot 2020-12-24 at 19 18 01" src="https://user-images.githubusercontent.com/15077780/103098789-1d082100-461d-11eb-84cf-5d6263012b3e.png">

**Comment by ened** [comment]
@Konoshenko can you please upload a reproducible example or share more details on what works / does not work. I can not follow the bug description 100%.

**Comment by Konoshenko** [comment]
@ened I'll try to make an example project tomorrow. What additional details can help you?

**Comment by ened** [comment]
You mention there's a crash - so a stack trace and logs would help.

Also have you tested it using the latest beta.5 version as well?

A reproducible example would be super - it will then become part of the test suite of this project.

**Comment by Konoshenko** [comment]
1. Stack trace log for you. [stack_trace.txt](https://github.com/fluttercommunity/flutter_uploader/files/5740375/stack_trace.txt)
2. Version witch I use in screenshot. 
<img width="595" alt="Screenshot 2020-12-24 at 22 12 14" src="https://user-images.githubusercontent.com/15077780/103103860-15547680-4635-11eb-96bf-013c2ec80cc6.png">


> You mention there's a crash - so a stack trace and logs would help.
> 
> Also have you tested it using the latest beta.5 version as well?
> 
> A reproducible example would be super - it will then become part of the test suite of this project.

**Comment by ened** [comment]
Ok confirmed, will fix tomorrow.

**Comment by ened** [comment]
@Konoshenko can you try the code in #134 ?

```
dependency_overrides:
  flutter_uploader:
    git:
      url: https://github.com/fluttercommunity/flutter_uploader
      ref: d1c3a2acc289064a444c4f9a047135392204a178
```
