### ISSUE TITLE
Trouble with flutter build apk. Build failed with an exception.

### ISSUE THREAD

**Issue by Konoshenko** [fluttercommunity/flutter_uploader#133]
When I use `flutter build apk ` or `flutter run --release` I get error.
But if I use `flutter build appbundle` build working correct. 

Look at the attached file.

[build_logs.txt](https://github.com/fluttercommunity/flutter_uploader/files/5741774/build_logs.txt)

**Comment by ened** [comment]
Do you get the same error when compiling the example app of this repository? 

Please share flutter version as well.

**Comment by Konoshenko** [comment]
Flutter 1.22.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 1aafb3a8b9 (6 weeks ago) • 2020-11-13 09:59:28 -0800
Engine • revision 2c956a31c0
Tools • Dart 2.10.4

When try `flutter build apk` on /example build work. But I use version 2.0.0 beta 3 in my project. This could be the reason?

**Comment by ened** [comment]
Looks like it may be a issue in your project setup. Will close unless you can upload a sample project that reproduces the error online.
