### ISSUE TITLE
Can we cancel one particular task not whole list?

### ISSUE THREAD

**Issue by kadnan0900** [fluttercommunity/flutter_uploader#138]
///
  /// Cancel all enqueued and running upload tasks
  ///
  Future<void> cancelAll() async {
    await _platform.invokeMethod<void>('cancelAll');
  }

  /// Be careful, clearing this list will clear this list and you won't have access to it anymore.
  Future<void> clearUploads() async {
    await _platform.invokeMethod<void>('clearUploads');
  }

**Comment by ened** [comment]
There should be a method called `cancel`:

```
  /// Cancel a given upload task
  ///
  /// **parameters:**
  ///
  /// * `taskId`: unique identifier of the upload task
  ///
  Future<void> cancel({@required String taskId}) async {
    await _platform.invokeMethod<void>('cancel', {'taskId': taskId});
  }
```

If this is not available, please try testing the latest 2.0.0 beta version.
