### ISSUE TITLE
can we cancel mupltipicker of each file ? i mean if i select 5 images at a time through FilePicker and i want to cancle one of them ? Is this possible or not in file_uploader_best_6?

### ISSUE THREAD

**Issue by kadnan0900** [fluttercommunity/flutter_uploader#143]

**Comment by kadnan0900** [comment]
I know their is two method in beta_6 cancelAll and cancel but they work on specific one task right if i select one 5 images at a time through file picker and send to enqueue it will consider that multiple images as one task.so i want to cancel one of them image. Is it possible in beta_6 or not ?

**Comment by kadnan0900** [comment]
@ened

**Comment by ened** [comment]
You can only cancel a task at a time, not single file within a task. If you want to cancel single files, then enqueue them separately.

**Comment by kadnan0900** [comment]
Thanks for the reply @ened
