### ISSUE TITLE
can we clear one specific task from memory ? i can see their is only one method which clear all task in beta_6 ?

### ISSUE THREAD

**Issue by kadnan0900** [fluttercommunity/flutter_uploader#145]

**Comment by kadnan0900** [comment]
@ened  ??

**Comment by kadnan0900** [comment]
///Clear a given upload task
  ///
  /// **parameters:**
  ///
  /// * `taskId`: unique identifier of the upload task
  ///
  Future<void> clearSpecificTask({@required String taskId}) async {
    await _platform.invokeMethod<void>('clearUpload', {'taskId': taskId});
  }

the method will be look like this if you update it will be very thank full.

**Comment by ened** [comment]
This will probably not be available as clearUploads calls pruneWork on android work manager. 

https://developer.android.com/reference/androidx/work/WorkManager

It's either remove all or nothing.

**Comment by kadnan0900** [comment]
is it possible to remove that particular task or all that tasks which is successfully uploaded to the server?

**Comment by ened** [comment]
Yes, but that is on the library user to implement. The uploader should do just uploading, not much more. The book-keeping as it is exposed right now (results available after uploads are finished) is just a convenience for app developers. I'm considering to drop it. @kadnan0900
