### ISSUE TITLE
MissingPluginException

### ISSUE THREAD

**Issue by Nemowxy** [fluttercommunity/flutter_uploader#146]
Sorry, I tried a lot of methods but still did not solve it. I would like to ask why this error occurs. The 1.2.1 version is correct, and 2.0.0-beta6 will be like this.
`======== Exception caught by services library ======================================================
The following MissingPluginException was thrown while activating platform stream on channel flutter_uploader/events/progress:
MissingPluginException(No implementation found for method listen on channel flutter_uploader/events/progress)

When the exception was thrown, this was the stack: 
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
<asynchronous suspension>
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
#2      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:540:29)
#3      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:526:64)
...
====================================================================================================

======== Exception caught by services library ======================================================
MissingPluginException(No implementation found for method listen on channel flutter_uploader/events/result)
====================================================================================================`
`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale
    zh-Hans-CN)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
[✓] Android Studio (version 4.1)
[!] IntelliJ IDEA Ultimate Edition (version 2020.2.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code (version 1.52.1)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (2 available)

! Doctor found issues in 2 categories.`

**Comment by qianxuechao** [comment]
http://blog.z7ge.com/archives/flutter-missingpluginexception-bu-yao-huang 希望能帮到你

**Comment by ened** [comment]
@Nemowxy please show more details on the stack trace and perhaps a bit of code that triggers it. Based on the details submitted, I can not help you.
