### ISSUE TITLE
javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

### ISSUE THREAD

**Issue by akhildexlock** [fluttercommunity/flutter_uploader#148]
I am using flutter uploader(1.2.0) in one of my projects for uploading audio files to my server. It worked fine for me but when the server updated with SSL (HTTPS), it couldn't upload my files. 
I have got an error like "javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.".

The server's SSL certificate is signed by CA and it is not expired. The uploading is working fine through iOS build of the same project and same library.

Could you please help me to resolve this issue.
Thanks in advance.

**Comment by miguelquo** [comment]
Same here.

**Comment by ened** [comment]
Is the server publicly available?

**Comment by miguelquo** [comment]
No sorry, but recently I just updated to 2.0.0-beta6 and seems like it works now, but the error message still shows.

**Comment by miguelquo** [comment]
I just figured out that the problem is not related to this library but the certificates of the server. To make it work you will need check your server, or change some configs in Okhttp to accept bad/wrong certificates.

**Comment by ened** [comment]
Thank you
