### ISSUE TITLE
Uploading audio not working

### ISSUE THREAD

**Issue by GhezaeGoitom** [fluttercommunity/flutter_uploader#150]
when i try to upload audio the request content-type is changed to "audio/mpeg" but the file is mp3

**Comment by ened** [comment]
OK, we will change this by removing the mime type detection logic from the plugin completely.

**Comment by GhezaeGoitom** [comment]
thank you @ened, could you give me any hints for temporary fix.

**Comment by ened** [comment]
Please take a look at the source code. You may be able to set the Content-Type header yourself.

**Comment by patelnirav48** [comment]
is this fixed already? now any audio file can be uploaded?

**Comment by GhezaeGoitom** [comment]
yes, it is working now.
