### ISSUE TITLE
Because flutter_uploader_example depends on flutter_uploader from path which requires SDK version >=2.12.0 <3.0.0, version solving failed.

### ISSUE THREAD

**Issue by gracegyu** [fluttercommunity/flutter_uploader#157]
When I run 'pub get' the example I meet below error

The current Dart SDK version is 2.12.0-141.0.dev.

Because flutter_uploader_example depends on flutter_uploader from path which requires SDK version >=2.12.0 <3.0.0, version solving failed.
pub get failed (1; Because flutter_uploader_example depends on flutter_uploader from path which requires SDK version >=2.12.0 <3.0.0, version solving failed.)

I don't want to upgrade flutter2. What should I do to resolve it.

**Comment by ened** [comment]
@gracegyu you could use the previous version `2.0.0-beta.6`.

In your pubspec file just refer to `flutter_uploader: 2.0.0-beta.6`
