### ISSUE TITLE
Unable to receive multiple files in one array on server side

### ISSUE THREAD

**Issue by bachras** [fluttercommunity/flutter_uploader#161]
Hi,

Thanks for great package. I am able to send single file and everything works perfectly fine, but when I try to send multiple files, I can access only first file. After I have realised that field name is same for all images which requires every file to have different field name in order to access all files on server side. Is there any way to send multiple files and access in one array on server side like $request->file('files') as array. Otherwise, I need to know all field name set from app which causes inconvenience. Thank you

**Comment by ened** [comment]
I think that is a server side problem. Please check how your backend handles multiple uploads sent with the same name.

**Comment by bachras** [comment]
I have managed to retrieve all the files in one array on server side. If someone struggle and uses Laravel as backed, just use $request->allFiles(). Thank you for prompt response once again @ened
