### ISSUE TITLE
Maximum number of concurrent tasks doesn't work in android

### ISSUE THREAD

**Issue by armendarabyan** [fluttercommunity/flutter_uploader#174]
I am trying to set concurrent tasks to 1 and it doesn't work both in my app and in example provided, please help
```xml 
<meta-data
         android:name="com.bluechilli.flutterupload.MAX_CONCURRENT_TASKS"
         android:value="1" />
```

**Comment by PeriyanAra** [comment]
Having the same issue. Uploads are being done parallel on android

**Comment by armendarabyan** [comment]
@ened Please review and merge my pull request
