### ISSUE TITLE
WorkerWrapper(26016): Worker result FAILURE for Work [ id=3ad40d26-67e6-48da-ab93-7c65fda47bf3, tags={ flutter_upload_task, com.bluechilli.flutteruploader.UploadWorker } ]

### ISSUE THREAD

**Issue by prakash-cr7** [fluttercommunity/flutter_uploader#179]
I am stuck on this error. can't even figure out what's causing it. plz help!

**Comment by rushikdave** [comment]
Hi, I am facing the same issue right now, please share with me if you have any solution to it.

**Comment by VictorLekweuwa** [comment]
I'm facing the same issue. Please, what is the fix for this error?

**Comment by VictorLekweuwa** [comment]
I tracked the original error on this thread down to this

`D/UploadWorker(16131): Failed to upload - taskId: 1779ce1f-e608-447e-8ca1-c39d48623f7e, code: upload_task_error, error: java.net.SocketException: Connection reset`
and
`D/UploadWorker(16131): Failed to upload - taskId: 1779ce1f-e608-447e-8ca1-c39d48623f7e, code: upload_task_error, error: java.net.SocketException: Broken pipe`

as discussed on this stack-overflow thread. [stack-overflow](https://stackoverflow.com/questions/61991876/getting-java-net-socketexception-connection-reset-error-in-socket-communication)

Is there a way to fix this? I get the same exact error for both flutter_uploader: ^3.0.0-beta.2 and flutter_uploader: ^1.2.1 for binary uploads.

**Comment by prakash-cr7** [comment]
In my case, it was my fault. sometimes file didn't get picked and throw this error. Make sure to check if file is not null.

**Comment by VictorLekweuwa** [comment]
In my case, I was using `UploadMethod.POST` instead of `UploadMethod.PUT`

**Comment by tomsawada** [comment]
@prakash-cr7 @VictorLekweuwa In my case I checked the file is not null and UploadMethod is POST, apparently the file gets picked correctly and starts upload, but then fails with the same error. 

Any suggestions are greatly appreciated. Thanks!

Function:
```
uploadBackground(int id, String csrf, String cookie, List tags,
      List<AssetEntity> list) async {
    File image = await list[0].file;
    String url = "redacted for privacy";
    if (image != null) {
      final taskId = await FlutterUploader().enqueue(
        MultipartFormDataUpload(
          url: url, //required: url to upload to
          files: [
            FileItem(path: image.path, field: 'file')
          ], // required: list of files that you want to upload
          method: UploadMethod.POST, // HTTP method  (POST or PUT or PATCH)
          headers: {"cookie": cookie},
          data: {
            "id": id.toString(),
            "csrf": csrf,
            "lastModified": list[0]
                .modifiedDateTime
                .millisecondsSinceEpoch
                .abs()
                .toString(),
            "tags": tags.toString()
          }, // any data you want to send in upload request
          tag: 'my tag', // custom tag which is returned in result/progress
        ),
      );
      return taskId;
    } else {
      print('image is null');
    }
  }
```


Console:
D/UploadWorker( 3305): attaching file: /storage/emulated/0/Pictures/IMG_20211115_184414.jpg
D/UploadWorker( 3305): Start uploading for f7a0bf46-e834-473e-a047-96970db642b0
D/UploadWorker( 3305): taskId: f7a0bf46-e834-473e-a047-96970db642b0, bytesWritten: 8192, contentLength: 146261, progress: 6
D/UploadWorker( 3305): taskId: f7a0bf46-e834-473e-a047-96970db642b0, bytesWritten: 16384, contentLength: 146261, progress: 11
D/UploadWorker( 3305): taskId: f7a0bf46-e834-473e-a047-96970db642b0, bytesWritten: 24576, contentLength: 146261, progress: 17
D/UploadWorker( 3305): taskId: f7a0bf46-e834-473e-a047-96970db642b0, bytesWritten: 32768, contentLength: 146261, progress: 22
D/UploadWorker( 3305): taskId: f7a0bf46-e834-473e-a047-96970db642b0, bytesWritten: 40960, contentLength: 146261, progress: 28
D/UploadWorker( 3305): taskId: f7a0bf46-e834-473e-a047-96970db642b0, bytesWritten: 49152, contentLength: 146261, progress: 34
D/UploadWorker( 3305): taskId: f7a0bf46-e834-473e-a047-96970db642b0, bytesWritten: 57344, contentLength: 146261, progress: 39
D/UploadWorker( 3305): taskId: f7a0bf46-e834-473e-a047-96970db642b0, bytesWritten: 65536, contentLength: 146261, progress: 45
D/UploadWorker( 3305): taskId: f7a0bf46-e834-473e-a047-96970db642b0, bytesWritten: 73728, contentLength: 146261, progress: 50
D/UploadWorker( 3305): taskId: f7a0bf46-e834-473e-a047-96970db642b0, bytesWritten: 81920, contentLength: 146261, progress: 56
D/UploadWorker( 3305): taskId: f7a0bf46-e834-473e-a047-96970db642b0, bytesWritten: 90112, contentLength: 146261, progress: 62
D/UploadWorker( 3305): taskId: f7a0bf46-e834-473e-a047-96970db642b0, bytesWritten: 98304, contentLength: 146261, progress: 67
D/UploadWorker( 3305): taskId: f7a0bf46-e834-473e-a047-96970db642b0, bytesWritten: 106496, contentLength: 146261, progress: 73
D/UploadWorker( 3305): taskId: f7a0bf46-e834-473e-a047-96970db642b0, bytesWritten: 114688, contentLength: 146261, progress: 78
D/UploadWorker( 3305): taskId: f7a0bf46-e834-473e-a047-96970db642b0, bytesWritten: 122880, contentLength: 146261, progress: 84
D/UploadWorker( 3305): taskId: f7a0bf46-e834-473e-a047-96970db642b0, bytesWritten: 131072, contentLength: 146261, progress: 90
D/UploadWorker( 3305): taskId: f7a0bf46-e834-473e-a047-96970db642b0, bytesWritten: 139264, contentLength: 146261, progress: 95
D/UploadWorker( 3305): taskId: f7a0bf46-e834-473e-a047-96970db642b0, bytesWritten: 146261, contentLength: 146261, progress: 100
I/WM-WorkerWrapper( 3305): Worker result FAILURE for Work [ id=f7a0bf46-e834-473e-a047-96970db642b0, tags={ flutter_upload_task, com.bluechilli.flutteruploader.UploadWorker } ]
