### ISSUE TITLE
iOS return 500 while using flutter uploader with version 1.x

### ISSUE THREAD

**Issue by neohboonyee99** [fluttercommunity/flutter_uploader#184]
For android the flutter uploader works fine, the server able to upload the data. But for iOS, I meet this issue.
![3f1086db-3486-42f2-9b66-d2523640280f](https://user-images.githubusercontent.com/58653173/123916729-901b9700-d9b4-11eb-93e8-50604b952625.jpg)

Then, I have tried the flutter uploader with version 3.0 beta, it didn't appear this error, but it straight went into this line first and the progress automatically = 100
 uploader.result.listen((result) {
    BotToast.showText(text:"Complete");
 }
 instead of this
 uploader.progress.listen((progress) {
     BotToast.showText(text:progress.progess.toString());
 }
 
then it automatically run 2nd time ( uploader.enqueue() ) then start from listening the progress=0. When the progress =100 and result = UploadTaskStatus.complete , it did toast the complete but my server couldn't receive any data from it.

**Comment by raphaelgurtner** [comment]
have you checked that the issue is not the content-type header? we had the same issue (server not receiving anything when the request came from iOS but worked fine on android) and setting no content-type header worked for MultipartFormDataUpload
Related issue #204

**Comment by waqadArshad** [comment]
@raphaelgurtner what does setting no content-type header means? Can you please tell me what to write? Here is my code:

```
await FlutterUploader().enqueue(
                    RawUpload(
                      url: uploadUrls[i],
                      // required: url to upload to
                      path: selectedVideos[i].path,
                      // required: list of files that you want to upload
                      method: UploadMethod.PUT,
                      // HTTP method  (POST or PUT or PATCH)
                      // headers: {"apikey": "api_123456", "userkey": "userkey_123456"},
                      tag: 'post video uploading', // custom tag which is returned in result/progress
                    ),
                  );
```
