### ISSUE TITLE
[question] How can you pass data to the background handler?

### ISSUE THREAD

**Issue by Pato05** [fluttercommunity/flutter_uploader#186]
Hi, I have noticed that you are able to specify a background handler, so that it can freely run in an isolate. Though, since Isolates do not share memory, how should you pass data between the main and the background isolate?
I need that for localization of the strings and also to keep track of each upload through an integer that increments after each upload.

Thanks in advance!

**Comment by lyio** [comment]
My understanding is that you would need to handle that yourself somehow.

The background isolate has a FlutterEngine attached so that you can access the WidgetsFlutterBinding, but there is no BuildContext and no locale information readily available.

And you would probably need to handle communication between the isolates via send and receive ports.

I have a similar problem as I need to keep track of the files that have already been uploaded because I need to trigger
additional network requests in that case.

**Comment by Pato05** [comment]
@lyio Yes, that's the main point, usually you can set up a sendPort when you spawn an isolate, so that you can have a communication between the GUI isolate and the background worker.
I've looked a bit into the source code or the internal documentation, but I couldn't find anything, that's why I asked here, and of course, you can't handle that on the GUI Isolate, which may die while the background one should not.

May you give me more information on how to do something similar through WidgetsFlutterBinding?
Also, thanks for answering

**Comment by ened** [comment]
Look at IsolateNameServer & register a named port which you can look up.

Also, `moor` supports multi-isolate operation and you may be able to persist data in there.

**Comment by Pato05** [comment]
@ened Oh, thanks, I didn't know anything like that actually existed, while regarding moor, I already use Hive as my database solution, which can also be modified from a separate Isolate.

**Comment by lyio** [comment]
@ened is the backgroundHandler always invoked? From the example I gather that you register the handler once and that the isolate is kept running.

But on the Android side the Isolate is only spun up when you actually schedule work. So is there one isolate per task?

**Comment by ened** [comment]
@lyio Should be one isolate only which is kept around but can be stopped at some point. Do you observe unexpected behavior?

**Comment by lyio** [comment]
well, at the moment I am not observing any behavior.

This is the handler: 
```dart
void uploaderBackgroundHandler() {
  WidgetsFlutterBinding.ensureInitialized();
  final _logger = Logger('uploaderBackgroundHandler');

  // Notice these instances belong to a forked isolate.
  final uploader = FlutterUploader();
  _logger.warning('started background isolate');
  uploader.progress.listen((task) {
    // application is in background and we have no idea, which tasks
    // need to be handled here
    _logger.severe('+++++++++++++++++++++++++++++++++++++++++++++++++++');
    _logger.severe(task);
    _logger.severe('+++++++++++++++++++++++++++++++++++++++++++++++++++');

    // probably persist the taskId somewhere
  });

  uploader.result.listen((event) {
    _logger.severe('---------------------------------------');
    _logger.severe(event);
    _logger.severe('---------------------------------------');
  });
}
```

None of the log statements are triggered.

I also have _regular_ listeners in my main isolate that listen for progress and result. Those are triggered as expected.

So, I am not sure what else to do. Is there anything I need to do apart from calling `setBackgroundHandler`?
