### ISSUE TITLE
Is there support for wi-fi only uploads

### ISSUE THREAD

**Issue by lyio** [fluttercommunity/flutter_uploader#187]
I know that Android WorkManager supports scheduling uploads for when there is a wi-fi connection. From what I gathered, the NSURLSessionConfiguration also supports restricting the uploads to wi-fi.

Will support for this be added to the plugin? Would this be more involved than adding a flag to the `UploadJob` and passing it all the way through to the native side?

**Comment by ened** [comment]
Yes this should be a flag in dart which is picked up by the native side.

**Comment by lyio** [comment]
The challenge with this approach is that the configuration is built immediately when the plugin is registered:

```
let sessionConfiguration = URLSessionConfiguration.background(withIdentifier: Keys.backgroundSessionIdentifier)
        sessionConfiguration.httpMaximumConnectionsPerHost = maxConcurrentTasks.intValue
        sessionConfiguration.timeoutIntervalForRequest = URLSessionUploader.determineTimeout()
        self.session = URLSession(configuration: sessionConfiguration, delegate: self, delegateQueue: queue)
```

This is the place, where the flag would need to be respected and added to the configuration: `sessionConfiguration.allowsCellularAccess = someFlag`.

Since this configuration is only available in the initializer and the session is supposed to be longlived, I don't see a way to schedule individual uploads with this flag.

My idea here was that the user has a setting in the App to restrict uploads to wi-fi networks. I assumed that it would make sense to put this flag into each and every upload so that you could change this setting on the fly so to speak.

For this to work, the session would need to be rebuilt every time an upload is scheduled. That seems wasteful and unnecessary.

Some Apps require a restart in case a setting like this is changed. So maybe it would be possible to pass this flag along when constructing the `FlutterUploader` itself.

Or put the flag in `SharedPreferences` and read it from there when initializing the plugin on the Swift side.

**Comment by ened** [comment]
@lyio could we have 2 sessions (wifi, wifi+cellular) and the uploader picks the right one depending on the flag?

**Comment by lyio** [comment]
Configuring the session for wi-fi only uploads could be achieved similarly to how the background handler is attached.

```
    await _platform.invokeMethod<void>('setBackgroundHandler', {
      'callbackHandle': handle,
    });
``` 

We could add a method on the channel `configureSession` and invoke this method after the channels have been registered with the appropriate flag.

This only applies to iOS, of course, because on Android the WorkManger takes the wi-fi restriction on a per job basis, iirc.

So this way we could delay constructing the session (or even the whole `UrlSessionUploader`) to when

> @lyio could we have 2 sessions (wifi, wifi+cellular) and the uploader picks the right one depending on the flag?

**Comment by lyio** [comment]
> @lyio could we have 2 sessions (wifi, wifi+cellular) and the uploader picks the right one depending on the flag?

I could give this a try. Would this impact the backchannel to the Dart side of things? We would also have two session identifiers. But the `taskId` is not generated based on this identifier anymore, so that would not be a problem

**Comment by ened** [comment]
@lyio Start by having 2 session objects in the swift plugin and choose between them according to the upload object (which needs a new constraint parameter, or boolean flag) passed. 

You may not need additional methods on Dart side & only extend the Upload object.

**Comment by lyio** [comment]
> @lyio Start by having 2 session objects in the swift plugin and choose between them according to the upload object (which needs a new constraint parameter, or boolean flag) passed.
> 
> You may not need additional methods on Dart side & only extend the Upload object.

I have started to do just that. I will get a PR to you today. The only problem atm is that I do not have an iPhone that has cellular data. :) 

My testing capabilities are limited right now.

**Comment by ened** [comment]
Send something over, I'm happy to give it a spin later. Please do extend the example project with a checkbox or similar.
Thank you for looking at this issue! :-)

**Comment by ened** [comment]
You have fixed it yourself. Thanks again.
