### ISSUE TITLE
Upload Task Id format

### ISSUE THREAD

**Issue by abinvp** [fluttercommunity/flutter_uploader#193]
Hi,

Thank you for this wonderful package. 

I noticed that the upload task id format is inconsistent in android and ios. While android gives us just the UUID, iOS has the package name also attached. My local database column had a length set only to accommodate the UUID so it was failing to insert.

I am using `uploader.enqueue(upload);`

Android: 405bc0ff-25b8-44ac-b724-26adccc7e7c6
iOS: chillisource.flutter_uploader.upload.background.869B1C87-9766-499E-9B87-E4D80E3BB3F4

Is this expected?

**Comment by lyio** [comment]
Kind of expected. On iOS the session identifier is part of the taskId. 

This might be leftover from when the taskId was not generated as a UUID.

**Comment by abinvp** [comment]
Makes sense. Thanks!
