### ISSUE TITLE
Fail to upload file in IOS

### ISSUE THREAD

**Issue by tranice** [fluttercommunity/flutter_uploader#204]
Hi , thanks for great work!
I use flutter_uploader 1.2.1 to upload file and photos to server, server code is asp.net core web api ,like following code:
public Response UploadFile(IFormFile file)
{
      /* code ...*/
}
everything is ok where in Android. 
but in IOS device：iphone 7 plus. it is not work.
from log, file had been uploaded ,but in server file is null（as code above）. 
log:
URLSessionDidCompleteWithError: upload completed
URLSessionDidCompleteWithError: response: {"returnValue":null,"isSuccess":false,"code":"0","description":"no file！"}, task: completed
URLSessionDidSendBodyData: taskId: chillisource.flutter_uploader.upload.background.13, byteSent: 390718, totalBytesSent: 390718, totalBytesExpectedToSend: 390718, progress:100.0
URLSessionDidReceiveData:
URLSessionDidCompleteWithError: chillisource.flutter_uploader.upload.background.13 with response: <NSHTTPURLResponse: 0x28285abc0> ...

would you please give some help?

**Comment by tranice** [comment]
it is the issue of content-type.

**Comment by waqadArshad** [comment]
@tranice what does setting no content-type header means? Can you please tell me what to write? Here is my code:

```
await FlutterUploader().enqueue(
                    RawUpload(
                      url: uploadUrls[i],
                      // required: url to upload to
                      path: selectedVideos[i].path,
                      // required: list of files that you want to upload
                      method: UploadMethod.PUT,
                      // HTTP method  (POST or PUT or PATCH)
                      // headers: {"apikey": "api_123456", "userkey": "userkey_123456"},
                      tag: 'post video uploading', // custom tag which is returned in result/progress
                    ),
                  );
```

**Comment by ened** [comment]
What content type is the file you are uploading? You need to match it using `Content-Type`.
