### ISSUE TITLE
Sends POST request instead of PUT when UploadMethod.PUT is selected

### ISSUE THREAD

**Issue by passsionforprogramming** [fluttercommunity/flutter_uploader#205]
Title is self explanatory. When looking at the dev tools, it shows that a POST is consistently sent even when UploadMethod.PUT is selected.

**Comment by ened** [comment]
@passsionforprogramming is this on Android or iOS ?

**Comment by ened** [comment]
@passsionforprogramming this seems to work, please use the beta version `3.0.0-beta.3`
