### ISSUE TITLE
Wrong file type when uploading video to firebase storage via upload url

### ISSUE THREAD

**Issue by Mussab00** [fluttercommunity/flutter_uploader#221]
When i upload a video to firebase storage via a uploadUrl it does work, but the file type is wrong. 

Code:
![image](https://user-images.githubusercontent.com/32457409/154854749-50bcd2ae-3d7f-49af-ba4b-416c21e703ae.png)

File in storage:
![image](https://user-images.githubusercontent.com/32457409/154854722-f5279ab8-c63f-4ac3-ba96-769ca680992b.png)

I'm on Prerelease: [[3.0.0-beta.4](https://pub.dev/packages/flutter_uploader/versions/3.0.0-beta.4)](https://pub.dev/packages/flutter_uploader/versions/3.0.0-beta.4)

**Comment by mudi256** [comment]
How do you solve that problem?

**Comment by spatialbits** [comment]
I'm not familiar with the firebase "type" property, but I assume it's derived from the content type.
I noticed in my app that iOS uploads did not have the content type header set correctly. The plugin allows you to set the content type manually, which worked for me.

On Android the content type header is already set correctly when uploaded.
