### ISSUE TITLE
enqueue data is Map<String, String>, must pass dynamic.

### ISSUE THREAD

**Issue by royibernthal** [fluttercommunity/flutter_uploader#45]
I'm using flutter uploader to upload files to Transloadit.

Their API expect a deep object passed in the request data, which I can't pass since FlutterUploader/enqueue() data only accepts Map<String, String>.

Would you be able to change it to Map<String, dynamic>?

Here's the code I need to execute:

```
String taskId = await _uploader.enqueue(
        url: "your upload link", //required: url to upload to
        files: [fileItem],
        method: UploadMethod.POST,
        data: {"template_id":"some_id","auth":{"key":"some_key","expires":"2020/02/04 16:01:47 00:00"}}
    );
```

auth is the object I can't pass, since data's properties can only be strings.

If I try to just change the signature myself to Map<String, dynamic>, I get the following error:

> [log] taskId: some_id
> [log] progress: Instance of 'UploadTaskProgress'
> [log] ex: taskId: some_id, status:UploadTaskStatus(4), statusCode:500, code:upload error, message:com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 23 path $.}, tag:null
> [log] stacktrace: java.lang.Thread.run(Thread.java:919)
> java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> androidx.work.Worker$1.run(Worker.java:85)
> com.bluechilli.flutteruploader.UploadWorker.doWork(UploadWorker.java:117)
> com.google.gson.Gson.fromJson(Gson.java:841)
> com.google.gson.Gson.fromJson(Gson.java:892)
> com.google.gson.Gson.fromJson(Gson.java:939)

So I guess it's not as simple as that.

**Comment by royibernthal** [comment]
@ened @onikiri2007 It'd be great to hear your thoughts on this.

**Comment by omar-vasquez-dev** [comment]
I had the same problem I solved it as follows 

`
             headers: {
              "Content-Type": "application/json"
            },
             data: { 
              "auth": json.encode(object)
              ...
             }
`

I hope I helped you

**Comment by agnoam** [comment]
Any news about this ?

**Comment by ened** [comment]
@royibernthal hi - did you solve the problem with the solution @omar-vasquez-dev suggested?

**Comment by ened** [comment]
Please manually encode the form fields. You can refer to the [integration test](https://github.com/fluttercommunity/flutter_uploader/blob/c955965ff947d37df554cfca665b88eacf9b75e8/example/integration_test/flutter_uploader_test.dart#L89) for details.
