### ISSUE TITLE
There are no items to upload error

### ISSUE THREAD

**Issue by TahaMalas** [fluttercommunity/flutter_uploader#48]
I've been trying to use `flutter_uploader` library in order to upload multiple images in the background.

This is the file path I am getting: 
`/storage/emulated/0/DCIM/Camera/IMG_20200322_211944.jpg`

And the result I am getting is this error in `onError` function

` code:invalid_files, message:There are no items to upload`

Also the app has permissions to reach the storage any suggestions?

**Comment by ened** [comment]
Please reopen a new issue against the latest beta version 2.0.0-beta.5 with detailed steps to reproduce the problem and errors logs.
