### ISSUE TITLE
IOS Crash

### ISSUE THREAD

**Issue by ThalapathySiva** [fluttercommunity/flutter_uploader#57]
*** First throw call stack:
(
        0   CoreFoundation                      0x00007fff23e3cf0e __exceptionPreprocess + 350
        1   libobjc.A.dylib                     0x00007fff50ba89b2 objc_exception_throw + 48
        2   CoreFoundation                      0x00007fff23e5dc34 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
        3   CoreFoundation                      0x00007fff23e4190c ___forwarding___ + 1436
        4   CoreFoundation                      0x00007fff23e43bf8 _CF_forwarding_prep_0 + 120
        5   libswiftCore.dylib                  0x00000001102ac58e $sSD8_VariantVyq_Sgxcig + 142
        6   libswiftCore.dylib                  0x000000011050d829 $sSDyq_Sgxcig + 9
        7   Runner                              0x000000010c94d9c3 $s16flutter_uploader26SwiftFlutterUploaderPluginC10urlSession_4task15didSendBodyData14totalBytesSent0no10Expe<…>

Works fine on android.

**Comment by KonAtPropertyMe** [comment]
I also got a crash on iOS if I tried to do more than one task at a time. By setting FUMaximumConnectionsPerHost and FUMaximumUploadOperation to 1 it fixed the problem for me -  it will single thread things, but that is better than crashing. I can't remember if my crash was the same one as above.

**Comment by ened** [comment]
A fixed version is now available: 2.0.0-beta.5. Looking forward to your feedback.
