### ISSUE TITLE
iOS: FlutterUploaderIsolate.[number].profiler EXC_BAD_ACCESS (code=1, ... ) while uploading

### ISSUE THREAD

**Issue by Curvel** [fluttercommunity/flutter_uploader#79]
I know here are other issues regarding **EXC_BAD_ACCESS** errors #39, but I'm not sure if they are related to each other or if this is a new one. If it's a duplicate, feel free to merge the issues or close the issue.

Anyway, when I simply try to upload one file I get sometimes this error which completely crashes the app.
![image](https://user-images.githubusercontent.com/13559511/90616435-b9548e00-e20d-11ea-8492-926108da3a63.png)
![image](https://user-images.githubusercontent.com/13559511/90618531-6e884580-e210-11ea-8cf2-12c43a13f512.png)
![image](https://user-images.githubusercontent.com/13559511/90618600-85c73300-e210-11ea-8fc3-8261e7df5a7c.png)
![image](https://user-images.githubusercontent.com/13559511/90618950-ef474180-e210-11ea-90ad-fbb6eb0bd3e7.png)

Commit: dbdc47d33905cc05ae939ab2d5bec2e678923703

My three plist keys are:
FUMaximumConnectionsPerHost: 1
FUMaximumUploadOperation: 1
FUTimeoutInSeconds: 3600

My call:
```
taskId = await FlutterUploader().enqueue(
        url: url,
        files: [FileItem(path: file.path)],
        method: UploadMethod.POST,
        data: data,
        headers: headers,
      );
```

Device Info:
- OS Version: iPhone OS 13.5 (Build 17G68)
- Hardware model: iPad7,5

**Comment by ened** [comment]
@Curvel Thank you for testing the branch, I appreciate it.

I will try to reproduce this issue asap.

**Comment by jayant1441** [comment]
Hey this error was thrown in simulator but in real device it works

**Comment by ened** [comment]
That is interesting. I almost never test in the simulator except for the automated tests. 😀

**Comment by stackved** [comment]
We are facing the same as well. Any solution?

**Comment by ened** [comment]
Please try it again with the latest version 2.0.0-beta.5 which includes a fix for this problem.
